name: date_input_formatter_pao
description: "Flutter TextInputFormatter for date inputs. Supports custom patterns (e.g., 'dd/MM/yyyy'), placeholders, and manages cursor position."
version: 0.1.0
homepage: "https://github.com/paooxide/date_input_formatter_pao"
repository: https://github.com/paooxide/date_input_formatter_pao
issue_tracker: https://github.com/paooxide/date_input_formatter_pao/issues
topics:
  - flutter
  - date
  - input
  - formatter
  - text-input

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
